markdown: kramdown
permalink: /:title/
url: http://nber1994.net
name: NBER1994.NET
author: nber1994
qq: xxxxxxxxx
email: m18710895391@163.com
beian: xxxxxxxxxx
cnzz: xxxxxx
weibo: xxxxxxxxx
github: nber1994
safe: true
paginate: 20
about: "nber1994"
